### ISSUE TITLE
No module named 'imp'

### ISSUE THREAD

**Issue by ftasbasi** [cuchi/jinja2-action#17]
```
Traceback (most recent call last):
  File "/app/entrypoint.py", line 5, in <module>
    from main import Context
  File "/app/main.py", line 2, in <module>
    from j2cli.context import read_context_data
  File "/usr/local/lib/python3.12/site-packages/j2cli/__init__.py", line 10, in <module>
    from j2cli.cli import main
  File "/usr/local/lib/python3.12/site-packages/j2cli/cli.py", line 8, in <module>
    import imp, inspect
ModuleNotFoundError: No module named 'imp'
```

If I use Python version as 3.12 then this error is thrown. According to [documentation](https://docs.python.org/3/library/imp.html), imp is deprecated in Python version 3.12.

**Comment by vvagaytsev** [comment]
@ftasbasi thanks for reporting this! I got into the same issue.

By the way, the documentation link is broken, it's `https://docs.python.org/3/library/imp.html` that points to the latest (currently 3.12) version that no longer supports `imp`. So it returns 404. You can fix it by changing it to `https://docs.python.org/3.11/library/imp.html` :)

**Comment by nyurik** [comment]
@cuchi all users of this great github action are affected it seems. Could you merge and release the #16 or fix it?  Someone even created a forked version, but obviously it is better to keep things maintained in one place. Thanks for all your hard work!

**Comment by cuchi** [comment]
Thank you so much everyone that reported and worked on this.

The latest release is available at https://github.com/cuchi/jinja2-action/releases/tag/v1.2.2

**Comment by nyurik** [comment]
@cuchi thanks so much for working on this!  Would you be interested in adding more (trusted) people to your project to help you maintain it? For example, the @ajeffowens has became a popular fork of your project, but clearly it is better to merge the efforts, rather than maintain multiple forks.  (I am assuming @ajeffowens would be ok with this)... or maybe some other devs?
