### ISSUE TITLE
[Enhancement] Allow variables to be set from a variable

### ISSUE THREAD

**Issue by thamara** [cuchi/jinja2-action#5]
In one project I wanted to use the action to create the body for the Release, considering information that I store in env variables or bash variables. I have tried a few things to make it work with jinja2-action, but I had no success as the variable was always being evaluated as a text.
It would be very interesting to have the action working with variables from the environment instead of being a hardcoded string in the configuration.

**Comment by cuchi** [comment]
That's an interesting feature!
The most convenient way to make this possible is to inject an `env` object into the engine, [like this suggestion](https://stackoverflow.com/a/27984610) tells.

That's not even hard to implement, maybe I'll open a PR on this until tomorrow.

Thank you!

**Comment by cuchi** [comment]
[Just published it.](https://github.com/cuchi/jinja2-action/releases/tag/v.1.2.0)

**Comment by thamara** [comment]
Thank you a lot for this! I was able to replace a very ugly code in my project for this action!
